# Regex patterns that match naming conventions. See here:
# https://en.wikipedia.org/wiki/List_of_generic_forms_in_place_names_in_the_United_Kingdom_and_Ireland
name_rules = {
    "aberP": ("(Aber)",),
    "acPaccPockS": ("(Ac)", "(Acc)", "(ock$)"),
    "afonSavonQ": ("(afon$)", "([aA]von)"),
    "arPardP": ("(Ar)", "(Ard)"),
    "ashP": ("(Ash)",),
    "astP": ("(Ast)",),
    "auchenPauchinPauchachP": ("(Auchen)", "(Auchin)", "(Auchach)"),
    "auchterP": ("(Auchter)",),
    "axPexePaxeAeskA": ("(Ax)", "(Exe)", "(Axe)", "(Esk)"),
    "aySeyS": ("(ay$)", "(ey$)"),
    "balPballaPballyPballP": ("(Bal)", "(Balla)", "(Bally)", "(Ball)"),
    "beckPbeckSbecA": ("(Beck)", "(beck$)", "(Bec)"),
    "benAbeinnQBeannQ": ("(Ben)", "([bB]einn)",  "([bB]eann)"),
    "bergQberryS": ("([bB]erg)", "([bB]erk)", "(berry$)"),
    "bexP": ("(Bex)",),
    "blenPblaenP": ("(Blen)", "(Blaen)"),
    "bostS": ("(bost$)",),
    "bournePbourneSburnS": ("(Bourne)", "(bourne$)",  "(burn$)"),
    "bradP": ("(Brad)",),
    "breP": ("(Bre)",),
    "burySboroughSbroughSburghS": ("(bury$)", "(borough$)", "(brough$)", "(burgh$)"),
    "bySbiP": ("(By$)", "(Bi)"),
    "cardenS": ("(carden$)", "(cardine$)"),
    "caerPcarP": ("(Caer)", "(Car)"),
    "casterSchasterScesterSceterScaisterQxeterS": ("(caster$)", "(chaster$)",
        "(cester$)", "(ceter$)", "([cC]aister)", "(xeter$)"),
    "cheapQchepQchippingA": ("([cC]heap)", "([cC]hep)", "(Chipping)"),
    "combeQcwmQcoombeQ": ("([cC]ombe)", "([cC]wm)", "([cC]oombe)"),
    "coedQ": ("([cC]oed)",),
    "cotScottS": ("(cot$)",  "(cott$)"),
    "craigPcraigAcragPcragAcreagPcreagAgraigPgraigA": ("(Craig)",
        "(Crag)", "(Creag)", "(Graig)"),
    "culP": ("(Cul)",),
    "cwmPcumP": ("(Cwm)", "(Cum)"),
    "cumI": ("(cum)",),
    "dalP": ("(Dal)",),
    "daleS": ("(dale$)",),
    "deanSdeanAdenSdonS": ("(dean$)", "(Dean)", "(don$)", "(den$)"),
    "dinPdinasP": ("(Din)", "(Dinas)"),
    "dolP": ("(Dol)", "(Dull)"),
    "donSdenS": ("(don$)", "(den$)"),
    "drumP": ("(Drum)",),
    "dubhSdubhPdubhAdowQdhuQduffQ": ("(Dubh)", "(dubh$)", "(Dow)", "(dow$)",
        "(Dhu)", "(dhu$)", "(Duff)", "(duff$)"),
    "dunPdumPdonPdouneP": ("(Dun)", "(Dum)", "(Don)", "(Doune)"),
    "eaglesPeglosPeglewsPecclesP": ("(Eagles)", "(Eglos)", "(Eccle)", "(Eglews)"),
    "eilianA": ("(Eilian)",),
    "eySayS": ("(ey$)", "(ay$)"),
    "eySeaSeigQ": ("(ey$)", "(ay$)", "([eE]ig)", "([eE]a)"),
    "fieldS": ("(field$)",),
    "finP": ("(Fin)",),
    "firthSfrithS": ("(firth$)", "(frith$)"),
    "firthQ": ("([fF]irth)",),
    "fordSforthS": ("(ford$)", "(forth$)"),
    "fosQfossQ": ("([fF]os)", "([fF]oss)"),
    "fossAforceA": ("(Foss)", "(Force)"),
    "garPgartP": ("(Gar)", "(Gart)"),
    "garthQ": ("([gG]arth)", ),
    "gateAgatePgateS": ("(Gate)", "(gate$)"),
    "gillPgillSghyllPghyllS": ("(Gill)", "(gill$)", "(Ghyll)", "(ghyll$)"),
    "glenPglenSglenA": ("(Gren)", "(gren$)"),
    "gowtA": ("(Gowt)",),
    "hamS": ("(ham$)",),
    "hitheShytheA": ("(hithe$)", "(Hythe)"),
    "holmQ": ("([hH]olm)",),
    "hopeS": ("(hope$)",),
    "howeA": ("(Howe)",),
    "hurstShirstS": ("(hurst$)", "(hirst$)"),
    "inchPinchAinschA": ("(Inch)", "(Insch)"),
    "ingS": ("(ing$)",),
    "ingIingeS": ("(ing)", "(ing$)"),
    "inverPinnerP": ("(Inver)", "(Inner)"),
    "keldAkeldS": ("(Keld)", "(keld$)",),
    "kethSchethS": ("(keth$)", "(cheth$)"),
    "kilP": ("(Kil)",),
    "kinP": ("(Kin)",),
    "kingP": ("(King)",),
    "kirkPkirkS": ("(Kirk)", "(kirk$)"),
    "knockPknockA": ("(Knock)",),
    "kylePkylesP": ("(Kyle)", "(Kyles)"),
    "lanPlhanPllanP": ("(Lan)", "(Lhan)", "(Llan)"),
    "langP": ("(Lang)",),
    "lawQlowQ": ("([lL]aw)", "([lL]ow)"),
    "leI": ("(le)",),
    "leaSleySleighSleighA": ("(lea$)", "(ley$)", "(leigh$)", "(Leigh)"),
    "linPllynA": ("(Lin)", "(Llyn)"),
    "lingPlyngP": ("(lingP)", "(lyngP)"),
    "lochAloughAloughS": ("(Loch)", "(Lough)", "(lough$)"),
    "magnaA": ("(Magna)",),
    "mawrAmawrS": ("(Mawr)", "(mawr$)",),
    "mereSmerS": ("(mere$)", "(mer$)"),
    "minsterAminsterS": ("(Minster)", "(minster$)"),
    "moreS": ("(more$)",),
    "mossPmossA": ("([mM]oss)",),
    "mouthS": ("(mouth$)",),
    "mynyddPmynyddA": ("(Mynydd)",),
    "nanPnansPnancP": ("(Nan)", "(Nans)", "(Nanc)"),
    "nantP": ("(Nant)",),
    "nessS": ("(ness$)",),
    "norP": ("(Nor)",),
    "pantA": ("(Pant)",),
    "parvaA": ("(Parva)",),
    "penP": ("(Pen)",),
    "pitP": ("(Pit)",),
    "polP": ("(Pol)",),
    "pontPpontS": ("(Pont)", "(pont$)"),
    "poolS": ("(pool$)",),
    "portSportA": ("(port$)", "(Port)"),
    "porthP": ("(Porth)",),
    "shawAshawS": ("(Shaw)", "(shaw$)"),
    "shepPshipP": ("(Shep)", "(Ship)"),
    "stanP": ("(Stan)", ),
    "steadS": ("(stead$)",),
    "sterS": ("(ster$)",),
    "stokeAstokeS": ("(Stoke)", "(stoke$)", ),
    "stowPstowAstowSstolS": ("(Stow)", "(stow$)", "(stol$)"),
    "strathP": ("(Strath)",),
    "streatQstreetQ": ("([sS]treet)", "([sS]treat)"),
    "sudPsutP": ("(Sud)", "(Sut)"),
    "swinP": ("(Swin)",),
    "tarnP": ("(Tarn)",),
    "thorpPthorpePthorpeSthorpesS": ("(Throp)", "(Thrope)", "(thorpe$)",
        "(thorpes$)"),
    "thwaiteStwattStwattA": ("(twaite$)", "(twatt$)", "(Twatt)"),
    "tillyPtulliePtullouchPtilliPtulliP": ("(TillyP)", "(TullieP)",
        "(TullouchP)", "(TilliP)", "(TulliP)"),
    "toftS": ("(toft$)",),
    "treP": ("(Tre)",),
    "treathQdreathS": ("([tT]reath)", "(dreath$)",),
    "tunPtunStonStonI": ("(tunP)", "(tun$)", "(ton$)", "(ton)"),
    "uponI": ("(upon)",),
    "wealdPwoldS": ("(Weald)", "(wold$)"),
    "whelP": ("(whelP)",),
    "wickSwichSwychSwykeS": ("(wick$)", "(wich$)", "(wych$)", "(wyke$)"),
    "wickS": ("(wick$)", ),
    "winP": ("(Win)", ),
    "worthSworthySwardineS": ("(worth$)", "(worthy$)", "(wardine$)"),
    "ynysA": ("(Ynys)",),
}


# Pick only feature codes that correspond to towns and cities, see
# http://www.geonames.org/export/codes.html
geofeat_rules = ("PPL", "PPLA", "PPLA2", "PPLA3", "PPLA4", "PPLC", "PPLCH",
    "PPLF", "PPLG", "PPLH", "PPLL", "PPLQ", "PPLR", "PPLS", "PPLW")
